---
- name: Start "{{ service }}"
  service:
    name: "{{ service }}"
    state: started
    enabled: true

- name: Enable firewalld port
  firewalld:
    port: "{{ port_number }}/tcp"
    state: enabled
    immediate: true
    permanent: true
